project_name: Mobject Gallery
repository_url: https://github.com/kolibril13/mobject-gallery
user_content_version: 0.15.1 (Manim) #  Note: this is NOT the version of the plywood gallery, but the version of the plywood content. When the plywood gallery is made for napari v0.4.15 , name this e.g. 0.4.15
description: |
favicon: icon.png
custom_footer: |
  <div style="position: fixed; bottom: 10px; right:10px"> Hello World! </a></div>
gallary_parameters_path: gallery_assets/gallery_parameters.json
